repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        description: Format changed lines in staged Syscape C++ sources.
        entry: git clang-format --staged --style file
        language: system
        files: \.(cpp|hpp)$
        pass_filenames: false
        require_serial: true
